### ISSUE TITLE
menu panel footer

### ISSUE THREAD

**Issue by kevkha** [frequent/multiview#12]
like Issue #7, in fullscreen mode the main panel is small and want to utilize all the space the content so I don't use global footer. I can't seem to get the footer to be displayed in the menu panel like in splitview plugin. The footer always span like the global footer.

**Comment by frequent** [comment]
You only want the footer in the menu panel, correct? If so, let me see if I can get it to work.

**Comment by kevkha** [comment]
Yes, that's correct. If possible please implement each panel has its own footer. I'm sure in certain page we want to show the footer in the main panel as well. Not the global footer. Thank you so much.

**Comment by frequent** [comment]
@kevkha 

Do you mean like this:  [sample](http://www.stokkers.mobi/jqm/multiview/test/fix_double.html)

In case the sample is correct, I did not change anything :-)

You have two options for toolbars:
a) Global = put them **inside wrapper** but **outside nested pages**. Only 1 globale header and footer per wrapper.
b) Local = put them **inside nested pages**

Of course your local footer will never be global, so on larger displays the footer will only be inside the menu-panel. But from what I understand, the above should be ok.

Please close if the issue is solved.

**Comment by kevkha** [comment]
Yes, that works perfectly. I had it outside of the page div before. No wonder why it didn't work. Move it right under the end of the content div solves the problem. Many thanks frequent.

**Comment by frequent** [comment]
good. the other is more tricky...
