### ISSUE TITLE
How can "All other pages can be loaded in externally"?

### ISSUE THREAD

**Issue by adam-acosta** [frequent/multiview#24]
"All other pages can be loaded in externally, so you can start with a multiview-shell and load pages as you need."

How does, for example, external.html (as opposed to #interal) need to be structured to simply load in the main panel keeping the menu panel intact?  External.html doesn't need to have the html structure on index.html with the menu structure etc right?

How does the link to external.html in index.html need to be constructed (with a data-panel="main", data-context, etc)?

**Comment by adam-acosta** [comment]
To be more clear, my goal here is to simply load external with transition into the main panel.  I don't want the index.html menu panel to be touched.

**Comment by adam-acosta** [comment]
seems like external.html is completely replacing index.html when all i want is to inject external into index.

**Comment by frequent** [comment]
shouldn't be a problem. It should work with regular links like:

```
 <a href="#internal_page" data-panel="your_panel_id"...

 <a href="folder/external.html" data-panel="your_panel_id" ....
```

ChangePage is the same. Be sure to specify a STRING as page to load. $('#internal') will not work, '#internal' will.

Also check my current [demo file](http://www.stokkers.mobi/jqm/multiview/test/fix_triplePop.html). All yellow links are external pages, all white links are internal pages. You will need at least one page per panel though. Otherwise the panel is black and I'm using this intial page (with data-show="first") as fallback on backwards navigation. 

or changePage calls:

**Comment by frequent** [comment]
Closing this. Please reopen, if you have anymore questions on this.
