### ISSUE TITLE
how can i make the Menu First column like split view?

### ISSUE THREAD

**Issue by mrjikey** [frequent/multiview#27]
how can i make the Menu First column like split view?
mean menu is fix there so i can scroll menu itself and the other content on the otherside

**Comment by mrjikey** [comment]
http://www.stokkers.mobi/jqm/multiview/test/over_triplePop.html#page_dialog

the dialog part look abit wierd right ? all the drop drop down list showed ... at bottom

**Comment by frequent** [comment]
re: first column: you dan set _data-scrollmode="overthrow"_ on the wrapper page. this will make all panels scroll individually. just doing this on one panel is too complicated because it requires a lot of css logic and I'm happy it works now... 

re: dialog: will be fixed in next commit. there is one bug in jqm, which goew back 2x if you close popup, select (, and dialog I believe). need to try and fix this today anyway for multiview so please check back later for the next commit

**Comment by frequent** [comment]
@mrjikey: commit is in. 

The crummy dialog is still there. I have not found a way to open "internal" pages as dialogs, so if you have

```
 wrapper.html
      panel
           page1
           page2
```

You cannot open _#page2#_ with data-rel="dialog", because to do so, page2 would have to be a child of the body (like in [multipage](http://jquerymobile.com/demos/1.1.0/docs/pages/multipage-template.html)) not a child of a pane (like in [multiview](http://www.stokkers.mobi/jqm/multiview/test/fix_triplePop.html)). If you want to use dialogs, make them external pages and load them into a panel like so:

```
 wrapper.html
      panel
           page1

 page2.html
```

Then you can do:   

```
  <a href="page2.html" data-rel="dialog">page2</a>
```

**Comment by mrjikey** [comment]
thxman
