### ISSUE TITLE
Scrolled column will not redraw

### ISSUE THREAD

**Issue by sstraus** [frequent/multiview#37]
On my iPad scrolling the menu column, in many cases will not redraw the list. Moreover the browser will wait the scroll to stop before render the list again. Any suggestion on how to fix this?

**Comment by frequent** [comment]
Not sure what you mean by redrawing? I'm using iPad1 and 3 and it seems to work ok unless I put in a large amount of form items (50+ Elements). Then scrolling will more or less stall.

For the latest commit, I have added a custom event: 

```
dimensionchange - recalibrate panels after adding/removing content (sort of like JQM's updatelayout event
```

Try if that helps by just setting:

```
$(window).trigger('dimensionchange');
```

I'm calling this whenever I add content via Ajax.

Another idea would be to set CSS:

```
position: relative;  /* optional */
-webkit-transform: translate3d(0,0,0);
```

On the page or scrollable element. Seems to be Steroids for scrolling although I'm not sure it does not cause any other problems on non iOS devices.

**Comment by sstraus** [comment]
Thank you. The new version performs better.
I'm already using using `-webkit-transform: translateZ(0)` but with no steroids at all.
Have you implemented a sort of progressive loading of the lists?

**Comment by frequent** [comment]
If you mean lazy loading of list items, no. 

But have a look here: [JQM lazyloader](http://dcarrith.github.com/jquery.mobile.lazyloader/)

**Comment by sstraus** [comment]
Thank you for the tip.

I found a strange behavior in the popover with the new release, clicking the back button inside, will go back the whole page, not just the popover.

S.

**Comment by sstraus** [comment]
Found, is an error at:

1813 multiview.js thisWrap is not defined.

**Comment by frequent** [comment]
Thanks for the pointer. It should be **thiswrap** not **thisWrap**... Just made a commit. Working on my site, so should be ok.

**Comment by sstraus** [comment]
When I talk about redrawing I mean the page that don't repaint after a scroll. It happen also on the main page that is not so big, just a page and a half. I scroll down and the second part of the page remain blank. But the content is there. If I tap the page the content react and sometime will show up.

On the iPad 1 is more evident this issue. Looks like a missing refresh event after scrolling.

Any suggestion because the app is unusable.

Btw on the desktop pc works like a sharm.

Thanks

**Comment by frequent** [comment]
And the section that does not redraw is a listview? 

I have tried with the pages I'm using multiview in and both iPad1 and iPad3 are rendering ok, but I don't have any large listviews in them. Have you tried the 

```
  $(window).trigger('dimensionchange');
```

on scrollstrop to see what happens. I'm using it to refresh panel dimensions when adding content, but I'm not sure it helps, because it's only re-calculating and setting panel heights and width based on content sections. 

Also, I don't think this is necessarily related to multiview (see [here](http://stackoverflow.com/questions/9807620/ipad-safari-scrolling-causes-html-elements-to-disappear-and-reappear-with-a-dela), [here](http://stackoverflow.com/questions/9046143/really-long-background-image-does-not-render-on-ipad-safari) or [here](http://stackoverflow.com/questions/8912218/iframe-content-not-rendering-under-scroll-in-ios5-ipad-iphone)). My guess would be the first link and the use of _translate_. Let me know if any of these help.

**Comment by sstraus** [comment]
Yes! With translateZ(0) was not working, with  translate3d(0, 0, 0) is fine.

``` javascript
using *:not(html) {
    -webkit-transform: translate3d(0, 0, 0);
}
```

will brake the multiview layout, I'm using 

``` javascript
[data-role="content"] div {
            -webkit-transform: translate3d(0,0,0);
        }
```

and it's fine.

Thanks you again!
