### ISSUE TITLE
An issue with getting mathml to show in a main-loaded external page

### ISSUE THREAD

**Issue by noahscales** [frequent/multiview#38]
Hi, Frequent.

Thanks again, for your help, and for producing multiview, it's still in the works for our project, and for a separate project of mine sometime after this one.

We're having an issue to do with mathml, and, separately but still importantly, failure of a script called MathJax to run (or even get loaded into the DOM, from what I can see), when it sits in an external page loaded into the main view of a splitview. 

I've tried the MathJax folks, who pointed out that their code should be loaded into the body, which, even if I place the script inside of, it still fails to appear in the code. 

Meanwhile, mathml placed inside a math block will render, and then vanish, I can see the rendering during the initial transition to the external page containing it but then it disappears entirely.

You can see examples of both problems in the test case I posted: 

http://www.noahjscales.com/multiview/wrapperandstartpages.htm

, then navigate to the external page.

I'm not sure if I missed a spot in your extensive docs that described how to handle javascript or events used in external pages, to ensure code is loaded properly. I didn't find anything, but I probably missed it, if you want to just me to it, I'll figure it out from those.

Thanks again,  you're busy after returning from work on another project, I know, so I recognize that you've a lot to do, and that your reply might have to wait.

-Noah

**Comment by frequent** [comment]
Hey Noah, do you mean my new readme.md ;-) ? 

I'm trying to put in a few hours this week to update the readme and start on an easier sample page, where you can just put together your options and layout. 
1. Regarding scrollbars.... missing a class, let me see if I can fix it right away.
2. Regarding your page:

If you check the source code of your link on Firebug. The 

```
  <math></math>
```

object is there, BUT it's **after** the div.content, not **inside**. 

I don't know how JQM handles elements outside div.content, but in your case, as you are using overthrow-mode, multiview fixes the content height to the avaialable screen height less toolbars and makes the content scrollable (= lock page, scroll content). 

As your math object is **outside** div.content, it's "sitting below the bottom edge of the screen" and can never be scrolled into view, because the page is locked and only what's inside content is scrollable... hope you understand what I mean. 

Easy fix: Make sure you append the math object to the div.ui-content, **NOT** to the div.ui-page

I just copy&pasted it in Firebug from there into div.ui-content. Looks like this:

[<img src="http://www.franckreich.de/jqm/math.jpg">](http://www.franckreich.de/jqm/math.jpg/)

If you need more help setting things up, we could also do some project/support on an hourly basis. That I can always fit into my schedule.

I will re-post on the scrollbars. If you need more help setting everything up, we could also talk about some sort of project/support on an hourly basis. 

Cheers,

Frequent

**Comment by frequent** [comment]
also, please close if "math" is working now.

**Comment by noahscales** [comment]
Hey, thanks, yes, the mathml is working, it should have gone in the content section in the first place, my eye missed the div closing the content section. More confusing because it did show up without multiview, despite being outside the content section, I suppose that's a JQM bug.

The documentation is older, I think, available through the stokkers.mobi  website..? It's nice, and extensive, I was not being sarcastic.

The MathJax rendering is most important, it turns out. 

I look forward to reading your new write-up and the simplified example, I'm hoping to learn the specifics of configuring back button (turning it on and off), and how to configure additional javascript libraries for use with JQM+multiview to ensure they load properly into the DOM. 

If there's more specific help needed to get MathJax working, I will consider hiring you short-term, after our initial prototype work is finished. I'm also going to dig into the source code more. In the meantime, I'll check the docs hoping for some description of handling 3rd-party libraries in addition to JQM+multiview.

Much obliged, Frequent. You're conscientious AND forgiving, always appreciated in a fellow software professional. I'm sure I'll learn a lot by browsing your coding work, btw, it's good stuff. 

Thanks for the tip about tableview.

Cheers.
