### ISSUE TITLE
One way ticket

### ISSUE THREAD

**Issue by vpixle** [frequent/multiview#39]
Media query works only once you narrowing the screen. It doesn't work once you (ex.) switch  the tablet to landscape.

**Comment by frequent** [comment]
Hey,

I'm not sure I understand. I have disabled changing the layout on resize, so if you shrink/enlarge the browser window, nothing should happen.

But if you switch orientation, the plugin should update and
- switch splitiview (landscape) to popover mode (portrait)
- run panelHeight and panelWidth to update panel dimensions

If that is not happening, please let me know what exactly is the problem with the media query, so I understand what you mean.

Also, you can trigger the plugins `dimensionchange` event to fire panelHeight/panelWidth manually.

**Comment by vpixle** [comment]
Hi,
Once you start on wide screen it shrinks (once) to one column layout, but
it won't change back.
There's either one extra  layout  change or one is missing.

Alex

2012/8/21 Sven Franck notifications@github.com

**Comment by frequent** [comment]
Ok. Understand. Let me check tonight.

**Comment by frequent** [comment]
@vpixle: ok. That the layout does not change when you shrink/increase screen size is on purpose :-) 

It's done in the `maineventbindings`,  line:

```
  $(window).on('orientationchange', function(event){    
      self.splitScreen(event);
      self.panelHeight("or");                   
      self.gulliver("or");
      });                       
```

Originally I was binding to both `orientationchange resize`, which I guess you are asking for.

However as the functions `popover()` and `splitview()` being triggered by `splitscreen(event)` and `panelHeight()` are really eating into resources, I removed `resize` from the binding when I went through the plugin trying to increase performance by avoiding unnecessary function calls.

The question I asked myself was, if it's necessary to include resize-based recalculation of the layout in a live system, because resize will not trigger once when you shrink the screen (more like 10 times). For every trigger the plugin reworks the layout and recalculates wrapper/panel/content width and height. 

You can add the `resize` event back in and tell me how it's working. Performance wise I think it really stalls the page when you resize.

If this is not what you mean, please re-open.
