### ISSUE TITLE
multiview for JQM 1.1

### ISSUE THREAD

**Issue by eoksman** [frequent/multiview#4]
I love your currently implementation. Do you have any plans to port it to JQM 1.1?

**Comment by frequent** [comment]
Sitting on it right now.

I'm basically done adapting to Jquery 1.7.1. and on()/offing() everything. 

The next tricky part will be the repositioning of popovers, because until JQM 1.0.x I could just attach popovers to fixed toolbars and have them repositioned along with header and footer. Since JQM now uses position:fixed I will need to port parts of the old fixed toolbar into my plugin, so the popover position will update when scrolling.

**Comment by frequent** [comment]
@eoksman:

JQM 1.1. version is online. Navigation more or less works. Still needs a lot of fine-tuning (espically for tablet and smartphone), but should be usable. 

Here is a template with [sample navigation](http://www.stokkers.mobi/jqm/multiview/sample-nav.html)

Closing this for now.
