### ISSUE TITLE
Panel position

### ISSUE THREAD

**Issue by scruffian** [frequent/multiview#8]
Hi

Is it possible to have a right panel as well as a left panel - so instead of menu, mid, main, the "mid" panel would be on the right - menu, main, mid?

Also, is it possible to change the name of the toggles for the "main" and "mid" panels when they appear at the top of "main"?

Thanks!

**Comment by frequent** [comment]
Hey

You need to make sure the "Main" panel is always on the **right** hand side, because it's margin-left is calcualted based on what panels are to the left of it. 

So you can do:
1) Single Panel - must be "Main" = Fullwidth
2) Splitscreen 2 Panels - x and  "Main"
3) Splitscreen 3 Panels -"Mid" and "Menu" and  "Main"

The panel names are only for plugin-internals things such as calculating widths. You can place any content you want in the respective panel, so instead of switching panel position, I would only switch contents. Maybe "Left" "Mid" "Right" would be better panel names... 

Regarding the button text, you can do the following:

1) Set global options for all multiview pages in your app (may be more than 1):

```
 // change the default text, theme, icon and iconpos
 menuTxt: 'Menu',  
 menuBtnTheme: 'a', //     
 menuBtnIcon: 'gear',
 menuBtnIconPos: 'left',

 midTxt: 'Mid',
 midBtnTheme: 'a',
 midBtnIcon: 'gear',
 midBtnIconPos: 'left',     
```

2) Alternatively you can set this on the respecitve panels by adding jqmData attributes like so:

```
 data-menu-txt ="my_custom_text"
 data-menu-theme="my_theme"
 data-menu-icon="my_icon"
 data-menu-iconpos="notext"
 ...
```

You can also remove the menu/mid button from the header and place it somewhere in the page (for example I'm using it to open a search menu, so the button is sitting next to my search input. To do this, just place 

```
data-drop-pop="true" 
```

to the wrapper element, that should contain the button. Before insert the plugin the button checks

a) is there a drop-pop element, if so place button there,
b) if not, is there a global header, if so place button there,
c) if not, is there a local header, if so place button on all local headers,
d) if not, place button in content section of active page

Hope that helps. I'm working on the plugin right now, so be sure to check out the latest commit tomorrow.

Cheers, Frequent

**Comment by frequent** [comment]
Closing this. Please re-open in case your problem isn't solved.
